# Generated by Django 2.2.4 on 2019-11-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectspsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
