# Generated by Django 2.2.4 on 2019-11-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectspsm', '0002_auto_20191108_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='foodcolor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdata',
            name='grocery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdata',
            name='oil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdata',
            name='spices',
            field=models.BooleanField(default=False),
        ),
    ]
